### ISSUE TITLE
introduce retry mechanism for client.batches.get

### ISSUE THREAD

**Issue by kacurez** [pocin/kbc-mailchimp-writer#8]
calling for get batch status sometimes fails with ConnectionError:

https://github.com/pocin/kbc-mailchimp-writer/blob/783ed791f49147f35dac128b11aabaeb34adb9f7/mcwriter/utils.py#L301-L302

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

<details>
<summary>full stack trace</summary>
<pre>
INFO:root:Batch job request sent {'id': 'd541760352', 'status': 'pending', 'total_operations':  ... onResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/mcwriter/writer.py", line 348, in run
    run_writer(client, params, tables, datadir=datadir)
  File "/src/mcwriter/writer.py", line 410, in run_writer
    created_lists=created_lists)
  File "/src/mcwriter/writer.py", line 318, in add_members_to_lists
    batch_action=_add_members_in_batch)
  File "/src/mcwriter/writer.py", line 303, in _do_members_action_and_wait_for_batch
    api_delay=SEQUENTIAL_REQUEST_DELAY)
  File "/src/mcwriter/utils.py", line 304, in wait_for_batch_to_finish
    batch_status = client.batches.get(batch_id)
  File "/usr/lib/python3.6/site-packages/mailchimp3/entities/batches.py", line 88, in get
    return self._mc_client._get(url=self._build_path(batch_id), **queryparams)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 25, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 93, in _get
    raise e
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 91, in _get
    r = requests.get(url, auth=self.auth)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
<pre>
</details>

It would be nice to have retry mechanism implemented for such case.

**Comment by pocin** [comment]
Never had this err before, but it seems reasonable thing to do.
I probably wont be able to do it the [proper way](https://www.peterbe.com/plog/best-practice-with-retries-with-requests) because the underlying mailchimp client doesn't use `requests.Session` in it's core, but I'll hardcode retry mechanism there

**Comment by kacurez** [comment]
appearently there is some simple retry mechanism in mailchimp client because another error that happend was

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us12.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/batches/334c9da7ef (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f30425a78d0>: Failed to establish a new connection: [Errno 110] Operation timed out',))`

<details>
<summary>full stack trace</summary>
<pre>
INFO:root:So far processed 1500 rows
INFO:root:Batch job request sent {'id': '33695d0b95', 'status': 'pending', 'total_operations':  ... ms, tables, datadir=datadir)
  File "/src/mcwriter/writer.py", line 410, in run_writer
    created_lists=created_lists)
  File "/src/mcwriter/writer.py", line 318, in add_members_to_lists
    batch_action=_add_members_in_batch)
  File "/src/mcwriter/writer.py", line 303, in _do_members_action_and_wait_for_batch
    api_delay=SEQUENTIAL_REQUEST_DELAY)
  File "/src/mcwriter/utils.py", line 304, in wait_for_batch_to_finish
    batch_status = client.batches.get(batch_id)
  File "/usr/lib/python3.6/site-packages/mailchimp3/entities/batches.py", line 88, in get
    return self._mc_client._get(url=self._build_path(batch_id), **queryparams)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 25, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 93, in _get
    raise e
  File "/usr/lib/python3.6/site-packages/mailchimp3/mailchimpclient.py", line 91, in _get
    r = requests.get(url, auth=self.auth)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us12.api.mailchimp.com', port=443): Max retries exceeded with url: /3.0/batches/334c9da7ef (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f30425a78d0>: Failed to establish a new connection: [Errno 110] Operation timed out',))
</pre>
</details>

maybe in such cases its better to fail with UserError and so let user know that there is a problem in connection. Don't know how difficult is that to catch tho.

**Comment by pocin** [comment]
Easy to catch all `requests` errors as user errors. Right now they appear as internal?

**Comment by kacurez** [comment]
yes they all appear as internal errors. I think it's a good idea to have all requests errors as user errors.

**Comment by pocin** [comment]
fixed in `tag 0.5.6` (I will make a PR next time!) and already deployed in keboola so should be ready in couple minutes

**Comment by pocin** [comment]
https://github.com/pocin/kbc-mailchimp-writer/blob/master/mcwriter/utils.py#L299

**Comment by kacurez** [comment]
perfect thanks!
